- application:
   name: chrome
   location: http://www.google.co.jp/chrome/
   architecture: [darwin, Ubuntu]
- application:
   name: yorufukuro
   location: http://sites.google.com/site/yorufukurou/
   architecture: [darwin]
