- application:
   name: chrome
   location: http://www.google.co.jp/chrome/
   architecture: [darwin, Ubuntu]
   
- application:
   name: yorufukuro
   location: http://sites.google.com/site/yorufukurou/
   architecture: [darwin]
   
- application:
   name: dropbox
   location: http://www.dropbox.com
   architecture: [darwin, Ubuntu]
   
- application:
   name: vlc
   location: http://www.videolan.org/vlc/
   architecture: [darwin]
   
- application:
   name: quicksilver
   location: http://www.macupdate.com/info.php/id/14831/quicksilver
   architecture: [darwin]

- application:
   name: witch
   location: http://veadardiary.blog29.fc2.com/blog-entry-271.html
   architecture: [darwin]

- application:
   name: keyremap4macbook
   location: http://pqrs.org/macosx/keyremap4macbook/index.html.ja
   architecture: [darwin]
   