#!/usr/bin/env python
#-*- mode: python -*-

"""
usage: garainstall [OPTIONS] root-path
"""
from optparse import OptionParser, OptionValueError
import os
import sys
import subprocess

def detect_os():
    """ only supports darwin and ubuntu"""
    if os.path.exists("/usr/bin/sw_vers"):
        return "darwin"
    elif os.path.exists("/usr/bin/lsb_release"):
        return "Ubuntu"
    else:
        raise

def main(argv):
    
